# Generated by Django 2.1 on 2018-08-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_No', models.CharField(max_length=20)),
                ('model_price', models.IntegerField()),
            ],
        ),
    ]
