# Generated by Django 2.1 on 2018-08-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='model_name',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
